import type { Metadata } from 'next'
import './_styles/reset.css'
import './_styles/globals.css'
import { ApolloWrapper } from '@/graphql/apollo/apollo-wrapper'
import Header from './_components/templates/Header'
import Hero from './_components/templates/Hero'
import Footer from './_components/templates/Footer'
import { Suspense } from 'react'
import Loading from './loading'
import PageWrapper from './_components/layouts/PageWrapper'
import Main from './_components/templates/Main'
import Analytics from './_components/libs/GoogleAnalytics'
import GoogleAdsenseScript from './_components/libs/GoogleAdsenseScript'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <head>
        <Analytics />
        <GoogleAdsenseScript />
      </head>
      <body>
        <PageWrapper>
          <Header />
          <ApolloWrapper>
            <Suspense fallback={<Loading />}>
              <Hero />
            </Suspense>
            <Main>{children}</Main>
          </ApolloWrapper>
          <Footer />
        </PageWrapper>
      </body>
    </html>
  )
}
