#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

yarn lint || {
    echo "\n ❌🟪 ESLint Check ${RED}Failed${NC}.\n"
    false;
}

yarn typecheck || {
    echo "\n ❌🟦 Type check ${RED}Failed${NC}.\n"
    false;
}

yarn build || {
    echo "\n ❌🟩 Next build ${RED}Failed${NC}.\n"
    false;   
}

echo "✅✅ ${GREEN}Build is completed... I am committing this now.${NC} ✅✅\n"